/**
 * docNumbers.ts
 *
 * All document numbers (orders, quotations, invoices, vendor bills) are
 * generated by the Postgres function `generate_doc_number(prefix, year)`.
 *
 * This replaces every client-side pattern like:
 *   `ORD-${year}-${String(orders.length + 1).padStart(4, '0')}`
 *
 * Why the old approach was broken:
 *   - Two users creating an order at the same time both read orders.length = N
 *     and both produce ORD-YYYY-000(N+1) → unique constraint violation.
 *   - Deleting an order reduces orders.length, so the next order reuses a
 *     number that previously existed.
 *   - The cache (React Query) may be stale, making the count wrong.
 *
 * The Postgres function uses pg_advisory_xact_lock to serialize concurrent
 * calls and a persistent counter table so deletions never affect future numbers.
 */

import { supabase } from '@/integrations/supabase/client';

type DocPrefix = 'ORD' | 'Q' | 'INV' | 'BILL';

/**
 * Generate the next document number for a given prefix.
 * Calls the `generate_doc_number` Postgres function via RPC.
 *
 * @param prefix - 'ORD' | 'Q' | 'INV' | 'BILL'
 * @param year   - defaults to current calendar year
 * @returns      - e.g. 'ORD-2026-0042'
 * @throws       - rethrows Supabase/Postgres errors so callers can toast them
 */
export async function nextDocNumber(
  prefix: DocPrefix,
  year: number = new Date().getFullYear()
): Promise<string> {
  const { data, error } = await (supabase as any).rpc('generate_doc_number', {
    p_prefix: prefix,
    p_year: year,
  });

  if (error) {
    throw new Error(`Failed to generate ${prefix} number: ${error.message}`);
  }

  // The function returns a scalar TEXT value
  return data as string;
}
